### ISSUE TITLE
Streamlining AMO theme by looking at existing modded CSS

### ISSUE THREAD

**Issue by RadWoodward** [overdodactyl/userContent-tweaks#12]
If it is confirmed that addons.mozilla.org is going to be themed, it may be beneficial to have a look at this [deprecated user stylesheet](https://userstyles.org/styles/25811/amo-dark-theme) and copy over what CSS we can.

**Comment by overdodactyl** [comment]
Thanks for this! I'll definitely give it a look....I'm curious how much of it will be usable, however, since Mozilla recently did a major redo of the AMO desing

**Comment by overdodactyl** [comment]
Unfortunately, this style sheet can't be used on the new site :(

Thanks though!
