### ISSUE TITLE
Download pop-up partially unthemed in Windows

### ISSUE THREAD

**Issue by RadWoodward** [overdodactyl/userContent-tweaks#13]
The Download pop-up has white text on a white background. Screenshot is on Windows 8.1.
![capture](https://user-images.githubusercontent.com/32779090/33726312-4061627a-db3a-11e7-9863-5605654f9e11.PNG)

**Comment by overdodactyl** [comment]
Thanks @RadWoodward!

Will get fixed ASAP

**Comment by overdodactyl** [comment]
@RadWoodward, should be fixed now.

Are you in the Nightly channel?

On a mac, I noticed this was an issue in Nightly, but not stable.

**Comment by RadWoodward** [comment]
Yes, I am using Nightly.

**Comment by overdodactyl** [comment]
Sounds good - thanks for the report.

I'll re-open if for some reason that didn't fix the issue on Windows as well.

**Comment by RadWoodward** [comment]
Related - the certificate popup has the same issue on Windows.

**Comment by overdodactyl** [comment]
Thanks @RadWoodward - should be good now :+1:
