### ISSUE TITLE
About:newtab theming

### ISSUE THREAD

**Issue by CaptaPraelium** [overdodactyl/userContent-tweaks#15]
I am running latest stable FF57 on Windows.

I've noticed some white areas and some of the theme's cyan braking through the colours I have set in my css file. 

My colors css looks like so:

```
:root {
	--primary-dark-color: #323234;  /* Color of FF dark theme nav-bar */
	--primary-light-color: #A6A6A6; /* Off white */
	--light-accent-color: #9c9d9f; /* Slightly darker off white */
	--dark-accent: #3C3C3C; /* darker shade of main color */
	--mid-way-color: #5c5a5a; /* inbetween main dark and light color */
	--primary-accent-color:  #0a84ff; 
	--primary-accent-color-dark: #45a1ff; 
}
```

When I edit a pinned site, this is the dialog I see:

![image](https://user-images.githubusercontent.com/22152831/33766914-b4a53b40-dc73-11e7-9fb7-b4b45f2be4c2.png)

In addition to this cyan and white, I also notice that the icons in the newtab page are behaving strangely. To be honst, I'm not sure what the intended behaviour is here. For some sits, I get a preview of the page, as the button to open it. For some, I get a preview of the page, overlayed by the page's favicon. For some, I get just the favicon.

Where the favicons are shown, if there is transparency, the background of the favicon is the theme's white colour. Also, the hyperlink text below the image is using the cyan colour again:

![image](https://user-images.githubusercontent.com/22152831/33767102-6f4ec2a4-dc74-11e7-8064-efe1fb55b69b.png)

Please let me know if I can help with this in any way.

**Comment by CaptaPraelium** [comment]
Sorry, I should have mentioned, that all of the about* pages seem to have this default theming showing the cyan colour. For example about:config. The background is the correct grey, but the text/buttons/checkboxes/etc are not the correct blue.

**Comment by overdodactyl** [comment]
Thanks - will look into.

I'm not a user of any of these pages/features...so I'm not positive about how it's "meant" to be.

**Comment by overdodactyl** [comment]
All these issues should now be fixed.

If not, please let me know and I'll re-open.
