### ISSUE TITLE
Theme Active tab highlight?

### ISSUE THREAD

**Issue by CaptaPraelium** [overdodactyl/userContent-tweaks#20]
As you may recall, I have been configuring this project to have the highlight colour match that of the default dark theme's active tab highlight, just for the sake of consistency.

![image](https://user-images.githubusercontent.com/22152831/33801986-c9368e76-ddc0-11e7-87cc-1f3f3dd6dedd.png)

It has occurred to me that with all the chrome modifications in this project, maybe it would even be possible to change this colour in the theme? Personally, I'm happy with blue-50, but it would be great to have the theme follow the customisations, rather than the other way around.

**Comment by overdodactyl** [comment]
Totally agree!

Easy thing to incorporate, but would add a lot of value in terms of the overall consistency/look.
