### ISSUE TITLE
Program filled up hard drive

### ISSUE THREAD

**Issue by OMTDesign** [overdodactyl/userContent-tweaks#292]
Hello,

I downloaded the 64bit version for linux. I ran the program by giving it "execute the file as a program" privileges then double clicked on the file.

No GUI appeared, and I forgot about the program and I continued to do other tasks on my laptop. The program ran for a few hours in the background, and it filled up 30GB of my hard drives space before terminating on its own.

I think I found the problem, the program failed to execute and created a system log file that is 30GB 
saying 

> Please input a valid number Please input a valid number...

![image](https://user-images.githubusercontent.com/39666543/67440052-8b85d380-f654-11e9-90e8-5b49b9dcefca.png)

![image](https://user-images.githubusercontent.com/39666543/67440134-c7b93400-f654-11e9-9244-15b451b467eb.png)

Firefox 69.0.2 
On Ubuntu 16.04.

**Comment by ljden** [comment]
Had the same happen to me, except I only noticed as one of my cores were running at 100%. 
`$ top` showed `systemd-journal` running at +100%. Opened the log with `journalctl -f` to track new log entries, found it continuously printing "Please input a valid number" searched the journal for the string and found shadowfox was the culprit.  
Running Ubuntu 18.04

**Comment by ljden** [comment]
Just did some digging, this is no longer an issue in the most current release (v2.2.0 - https://github.com/SrKomodo/shadowfox-updater/releases)
