### ISSUE TITLE
"Tooltips" and "Titlebar" styles on macOS dark mode

### ISSUE THREAD

**Issue by setanarut** [overdodactyl/userContent-tweaks#293]
I did the installation via homebrew.
```
$ brew install srkomodo/tap/shadowfox-updater
$ shadowfox
```
then I activated the dark mode.
`$ defaults write org.mozilla.firefox NSRequiresAquaSystemAppearance 0`
`$ defaults write org.mozilla.crashreporter NSRequiresAquaSystemAppearance 0`
`$ defaults write org.mozilla.plugincontainer NSRequiresAquaSystemAppearance 0`

Everything is dark and working properly(open/save file browser, alert windows)

<img width="559" alt="Ekran Resmi 2019-10-25 17 50 27" src="https://user-images.githubusercontent.com/36481442/67581069-0bdd2f00-f750-11e9-8681-043459f6902d.png">

<img width="839" alt="Ekran Resmi 2019-10-25 17 46 27" src="https://user-images.githubusercontent.com/36481442/67581292-70988980-f750-11e9-9f1c-0667f2120142.png">

Except for a few things,  tooltips and window titlebars colors are wrong after enabling dark mode.

<img width="728" alt="Ekran Resmi 2019-10-25 17 45 07" src="https://user-images.githubusercontent.com/36481442/67580950-d20c2880-f74f-11e9-90ee-68c4f08411fe.png">

system information;

macOS Catalina 10.15
Firefox 70

**Comment by hazarek** [comment]
[https://bugzilla.mozilla.org/buglist.cgi?quicksearch=dark+mode](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=dark+mode)

this is not a shadowfox issue. closed

**Comment by setanarut** [comment]
fix for tooltips add to userChrome.css

```
tooltip {
-moz-appearance: none !important;
color: #ffffff !important;
background-color: #1f1f1f !important;
opacity: 1 !important;}
```
