### ISSUE TITLE
Firefox 72

### ISSUE THREAD

**Issue by moonlitglare** [overdodactyl/userContent-tweaks#300]
![image](https://user-images.githubusercontent.com/20742787/72029139-f8bc0480-3252-11ea-8fab-1fafdf0cb8e3.png)

I downloaded FF72 and so much stuff is broken. Any menu is transparent.

**Comment by overdodactyl** [comment]
Unfortunately not much I can do with "so much stuff is broken."  

Try adding the settings mentioned in #285 and restart Firefox.

If things still are broken, please open one issue per problem and include all the information asked for in the issue template.
