### ISSUE TITLE
Firefox 73 login, bookmarks manager and history is white

### ISSUE THREAD

**Issue by AccessDenied420** [overdodactyl/userContent-tweaks#303]
This is on Windows 10 x64. Everything else is dark but when you open the bookmarks manager and show full history, they are bright white. Also the login prompt if you have a master password is now white.

**Comment by afgks** [comment]
Same here.

**Comment by act-of-reason** [comment]
I fixed this on my Firefox profile by editing the UserChrome.css and UserContent.css files.

Open each file in Notepad and search for .xul and replace it with .xhtml

Save each file and reload Firefox.

UserChrome.css had 11 entries of .xul, UserContent.css had 3 entries of .xul

**Comment by AccessDenied420** [comment]
I dont have either of those files in my FireFox profile folder.

**Comment by AccessDenied420** [comment]
> I fixed this on my Firefox profile by editing the UserChrome.css and UserContent.css files.
> 
> Open each file in Notepad and search for .xul and replace it with .xhtml
> 
> Save each file and reload Firefox.
> 
> UserChrome.css had 11 entries of .xul, UserContent.css had 3 entries of .xul

Thank you!
