### ISSUE TITLE
White outline around menus

### ISSUE THREAD

**Issue by CaptaPraelium** [overdodactyl/userContent-tweaks#79]
FF nightly (60.0a1) on windows... Have this white outline around any menus

![image](https://user-images.githubusercontent.com/22152831/37125496-0d6acd38-22c1-11e8-908a-658129395113.png)

Sorry, I'm still trying to learn CSS :/ I don't know if this is border or padding or what lol

**Comment by overdodactyl** [comment]
Gahhh.  FF 60 has been making things hard on me haha.

Are you using the normal `userChrome.css` or the `userChrome_windows.css` one?

**Comment by CaptaPraelium** [comment]
Same here. It's breaking lots of stuff. 
Honestly not sure, I just used the updater script.... Which is great BTW.

**Comment by overdodactyl** [comment]
Glad you're enjoying the updater script!  So you're using the normal `userChrome.css` file then.

Hmm.  I wonder if it's worth changing the Windows version to grab `userChrome_windows.css` until [this](https://github.com/overdodactyl/ShadowFox/wiki/Known-Problems#styling-for-specific-oss-not-going-into-effect) FF bug is fixed in 59.  

Then again, I'm not sure it would be good to switch it, as 59 is supposed to be out in less than a week and I feel like not many people are going to be frequently updating the updater script...

**Comment by overdodactyl** [comment]
You can try

```css
menupopup {
   border: none !important;
}
```

but that truly is a shot in the dark. 

And yaaa...this is a frustrating buggo

**Comment by overdodactyl** [comment]
Maybe give this a try @CaptaPraelium,

```css
#contentAreaContextMenu {
    border: none !important;
}
```

**Comment by loopy750** [comment]
Hi. Looks like you changed the border colour to --in-content-page-color, I wasn't sure if that was intentional or not.

**Comment by overdodactyl** [comment]
Oof.  My bad guys, I must have messed that up when I was doing some of the variable replacements...wasn't intentional.

This line I assume?

https://github.com/overdodactyl/ShadowFox/blob/b30b481747c127fbd157df5154614af4c582612f/userChrome-files/context_menus.css#L99-L103

**Comment by loopy750** [comment]
Yep that's the one. Also if you use 

menupopup menu[_moz-menuactive="true"],
menuitem[_moz-menuactive="true"] {

to replace

menu[_moz-menuactive=true],
menuitem:hover,
menuitem[_moz-menuactive=true],
menupopup menu:hover {

it will restore the macOS highlight blinking effect when clicking a menu item.

**Comment by overdodactyl** [comment]
Perfect, many thanks @loopy750!  Got the border fixed and updated the menu items.

Sorry for the silly mistake!

Also, @CaptaPraelium...I wasn't thinking very straight earlier apparently.  If you're using FF 60 then your browser no longer has the bug that necessitated the special Windows userChrome file....so you can change your updater script back to the original.
